server:
  port: 3004

eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 

spring:
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-catalog
          uri: http://localhost:3001
          predicates:
            - Path=**/product/**
        - id: shopping-cart
          uri: http://localhost:3002
          predicates:
            - Path=**/cart/**
            

